### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by krshrimali** [krshrimali/context-pilot-rs#12]
Following are some ideas that need to be implemented before the first version of this tool goes live:

* [ ] DB Sharding
* [ ] Compress JSON files to avoid bloating
* [ ] Empower users to decide what they want to do:
    * Add option for the git blame threshold (default = 5)
    * Add option whether to save the output in the DB
    * Add option to refresh / clear the DB
    * Add option to change the interval for refreshing the DB (default ~~ 1 day?)
    * Add option to give users ability to change the output limit
    * Add option to allow "files that don't exist" to be shown as outputs (default = False)
* [ ] Add `creation_time, last_modified_time` to the DB
* [ ] Write unit tests for each method written
* [ ] Write tests to ensure the output for `git blame` calls is as expected. ( in case of any breaking change ) -- this will be a GitHub workflow that runs in intervals
* [ ] Give users details a confidence score on each context file
